language: python
python:
    - "2.7"
    - "pypy"
install: "pip install -r requirements.txt"
script:
    - python setup.py install
    - cd tests && py.test
    - cd examples/sejong && python test.py
